apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-nginx-deployment
  namespace: kube-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php-nginx
  template:
    metadata:
      labels:
        app: php-nginx
    spec:
      containers:
      - name: php-nginx
        image: trafex/php-nginx
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: timezone
          mountPath: /etc/localtime
      volumes:
      - name: timezone
        hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
---
apiVersion: v1
kind: Service
metadata:
  name: php-nginx-service
  namespace: kube-system
spec:
  selector:
    app: php-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
